# Practical 1

__AIM:__  Introduction to Python,Numpy,Sklearn

## Table of Contents

1. [Variables and Data Types](#variables-and-data-types)
2. [Operators](#operators)
3. [Control Structures](#control-structures)
4. [Functions](#functions)
5. [Data Structures](#data-structures)
6. [Input and Output](#input-and-output)
7. [Modules and Packages](#modules-and-packages)

## 2. Variables and Data Types <a id='variables-and-data-types'></a>

### Variables

In [18]:
# Variable assignment
x = 5
name = "Ashish Vinod"

# Numeric types
integer_num = 10
float_num = 3.14

# Strings
name = "Ashish Vinod"
sentence = 'Hello, World!'

# Boolean
is_python_fun = True

print(x)
print(name)
print(sentence)
print(is_python_fun)

5
Ashish Vinod
Hello, World!
True


## 3. Operators <a id='operators'></a>

In [19]:
# Arithmetic operators
add = 10 + 5
sub = 10 - 5
multi = 10 * 5
div = 10 / 5
intdiv = 10 % 3
exp = 10 ** 2

# Comparison operators
is_greater = 10 > 5
is_equal = 10 == 5
is_not_equal = 10 != 5

# Logical operators
and_condition = (10 > 5) and (5 < 3)
or_condition = (10 > 5) or (5 < 3)
not_condition = not (10 > 5)

# Print statements
print("Addition:", add)
print("Subtraction:", sub)
print("Multiplication:", multi)
print("Division:", div)
print("Integer Division (Modulus):", intdiv)
print("Exponentiation:", exp)

print("Is 10 greater than 5?:", is_greater)
print("Is 10 equal to 5?:", is_equal)
print("Is 10 not equal to 5?:", is_not_equal)

print("AND condition:", and_condition)
print("OR condition:", or_condition)
print("NOT condition:", not_condition)


Addition: 15
Subtraction: 5
Multiplication: 50
Division: 2.0
Integer Division (Modulus): 1
Exponentiation: 100
Is 10 greater than 5?: True
Is 10 equal to 5?: False
Is 10 not equal to 5?: True
AND condition: False
OR condition: True
NOT condition: False


## 4. Control Structures <a id='control-structures'></a>

In [20]:
# If statement
if x > 0:
    print("x is positive")

# If-else statement
if x % 2 == 0:
    print("x is even")
else:
    print("x is odd")

# While loop
while x > 0:
    print(x)
    x -= 1

# For loop
for i in range(5):
    print(i)

x is positive
x is odd
5
4
3
2
1
0
1
2
3
4


## 5. Functions <a id='functions'></a>

In [21]:
# Function definition
def greet(name):
    print("Hello,", name)

# Function call
greet("Ashish Vinod")

Hello, Ashish Vinod


## 6. Data Structures <a id='data-structures'></a>

In [22]:
# Lists
my_list = [1, 2, 3, 4, 5]

# Tuples
my_tuple = (1, 2, 3)

# Dictionaries
my_dict = {'a': 1, 'b': 2, 'c': 3}

# Print statements
print("List:", my_list)
print("Tuple:", my_tuple)
print("Dictionary:", my_dict)


List: [1, 2, 3, 4, 5]
Tuple: (1, 2, 3)
Dictionary: {'a': 1, 'b': 2, 'c': 3}


## Operations on Lists
### Accessing elements


In [23]:
print(my_list[0])  # Output: 1
print(my_list[-1]) # Output: 5

1
5


In [24]:
# Slicing
print(my_list[1:3]) # Output: [2, 3]

[2, 3]


In [25]:
# Modifying elements
my_list[0] = 0
print(my_list) # Output: [0, 2, 3, 4, 5]

[0, 2, 3, 4, 5]


In [26]:
# Adding elements
my_list.append(6)
print(my_list) # Output: [0, 2, 3, 4, 5, 6]

[0, 2, 3, 4, 5, 6]


In [27]:
# Removing elements
my_list.remove(3)
print(my_list) # Output: [0, 2, 4, 5, 6]

[0, 2, 4, 5, 6]


### Operations on Tuple

In [28]:
# Accessing elements
print(my_tuple[0]) # Output: 1

1


In [29]:
# Slicing
print(my_tuple[1:]) # Output: (2, 3)

(2, 3)


### Operations on Dictionaries

In [30]:
# Accessing elements
print(my_dict['a']) # Output: 1

1


In [31]:
# Modifying elements
my_dict['d'] = 4
print(my_dict)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [32]:
# Removing elements
del my_dict['b']
print(my_dict)

{'a': 1, 'c': 3, 'd': 4}


## 7. Input and Output <a id='input-and-output'></a>

In [33]:
# Input
name = input("Enter your name: ")

# Output
print("Hello,", name)

Enter your name:  Ashish Vinod


Hello, Ashish Vinod


## 8. Modules and Packages <a id='modules-and-packages'></a>

In [34]:
# Importing modules
import math
print(math.sqrt(16))

4.0


# Pandas

In [35]:
import pandas as pd


In [36]:
data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)


0    10
1    20
2    30
3    40
dtype: int64


In [37]:
data = {
    'Column1': [1, 2, 3],
    'Column2': ['A', 'B', 'C']
}
df = pd.DataFrame(data)
print(df)


   Column1 Column2
0        1       A
1        2       B
2        3       C


In [38]:
# From a dictionary
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})
print(df)

# From a CSV file
df = pd.read_csv('demodata.csv')

# From a list of lists
df = pd.DataFrame([[1, 2], [3, 4]], columns=['A', 'B'])


   A  B
0  1  4
1  2  5
2  3  6


In [39]:
# Display the first few rows
print(df.head())



   A  B
0  1  2
1  3  4


In [40]:
# Display the last few rows
print(df.tail())


   A  B
0  1  2
1  3  4


In [41]:
# Get the shape of the DataFrame
print(df.shape)

# Get information about the DataFrame
print(df.info())


(2, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      int64
 1   B       2 non-null      int64
dtypes: int64(2)
memory usage: 164.0 bytes
None


In [42]:

# Get statistical summaries
print(df.describe())



              A         B
count  2.000000  2.000000
mean   2.000000  3.000000
std    1.414214  1.414214
min    1.000000  2.000000
25%    1.500000  2.500000
50%    2.000000  3.000000
75%    2.500000  3.500000
max    3.000000  4.000000


# Indexing and Selection

In [43]:
print(df['A'])

0    1
1    3
Name: A, dtype: int64


In [44]:
# Select multiple columns

print(df[['A', 'B']])


   A  B
0  1  2
1  3  4


In [45]:
# Select rows by index position

print(df.iloc[0])


A    1
B    2
Name: 0, dtype: int64


In [46]:
# Select rows by index label
print(df.loc[0])

A    1
B    2
Name: 0, dtype: int64


In [47]:
# Select a range of rows
print(df.iloc[0:2])

   A  B
0  1  2
1  3  4


# Data Manipulation

In [48]:
# Rename a column
df = df.rename(columns={'A': 'Alpha'})
print(df)

   Alpha  B
0      1  2
1      3  4


In [49]:
# Fill missing values
df.fillna(0, inplace=True)

In [50]:
# Drop missing values
df.dropna(inplace=True)

In [51]:
# Data Aggregation
grouped = df.groupby('Alpha').mean()

# Aggregate data
aggregated = df.agg({
    'Alpha': ['mean', 'sum'],
    'B': ['max']
})

# Print statements
print("Grouped Data by 'Alpha' with Mean:\n", grouped)
print("\nAggregated Data:\n", aggregated)


Grouped Data by 'Alpha' with Mean:
          B
Alpha     
1      2.0
3      4.0

Aggregated Data:
       Alpha    B
mean    2.0  NaN
sum     4.0  NaN
max     NaN  4.0


# Sorting and Filtering

In [71]:
# Sort by a column
df_sorted = df.sort_values(by='B')

# Filter rows based on condition
df_filtered = df[df['B'] > 5]

# Print statements
print("DataFrame sorted by column 'B':")
print(df_sorted)

print("\nDataFrame filtered where 'B' > 5:")
print(df_filtered)


DataFrame sorted by column 'B':
   Alpha  B
0      1  2
1      3  4

DataFrame filtered where 'B' > 5:
Empty DataFrame
Columns: [Alpha, B]
Index: []


In [72]:
import pandas as pd

# Merging DataFrames
df1 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})
df2 = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})
merged_df = pd.merge(df1, df2, on='key', how='inner')

# Joining DataFrames
df3 = df1.set_index('key')
df4 = df2.set_index('key')
joined_df = df3.join(df4, lsuffix='_left', rsuffix='_right')

# Print statements
print("Merged DataFrame:")
print(merged_df)

print("\nJoined DataFrame:")
print(joined_df)


Merged DataFrame:
  key  value_x  value_y
0   A        1        4
1   B        2        5

Joined DataFrame:
     value_left  value_right
key                         
A             1          4.0
B             2          5.0
C             3          NaN


In [73]:
joined_df

value_left  value_right
key                         
A             1          4.0
B             2          5.0
C             3          NaN

# Numpy

In [55]:
import numpy as np

In [56]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [57]:
# Create an array of zeros
zeros = np.zeros((3, 4))
print(zeros)

# Create an array of ones
ones = np.ones((2, 3))
print(ones)

# Create an array with a range of values
range_arr = np.arange(10)  # From 0 to 9
print(range_arr)

# Create an array with evenly spaced values
linspace_arr = np.linspace(0, 1, 5)  # 5 values from 0 to 1
print(linspace_arr)

# Create an identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [58]:
# Shape of an array
print("Shape:", matrix.shape)

# Dimensions (rank) of an array
print("Dimensions:", matrix.ndim)

# Size of an array (total number of elements)
print("Size:", matrix.size)

# Data type of array elements
print("Data type:", matrix.dtype)


Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int32


In [59]:
# Accessing elements
print("Element at (1, 2):", matrix[1, 2])

# Slicing
print("First row:", matrix[0])
print("First column:", matrix[:, 0])

# Advanced slicing
print("Submatrix:\n", matrix[0:2, 1:3])


Element at (1, 2): 6
First row: [1 2 3]
First column: [1 4]
Submatrix:
 [[2 3]
 [5 6]]


In [60]:
# Element-wise operations
arr = np.array([1, 2, 3, 4])
print("Add 5:", arr + 5)
print("Multiply by 2:", arr * 2)

# Universal functions (ufuncs)
print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))

# Matrix operations
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix addition
print("Matrix addition:\n", matrix1 + matrix2)

# Matrix multiplication
print("Matrix multiplication:\n", np.dot(matrix1, matrix2))


Add 5: [6 7 8 9]
Multiply by 2: [2 4 6 8]
Square root: [1.         1.41421356 1.73205081 2.        ]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Matrix addition:
 [[ 6  8]
 [10 12]]
Matrix multiplication:
 [[19 22]
 [43 50]]


In [61]:
# Reshape an array
reshaped = arr.reshape((2, 2))
print("Reshaped array:\n", reshaped)

# Flatten an array
flattened = reshaped.flatten()
print("Flattened array:", flattened)

# Concatenate arrays
concat = np.concatenate([matrix1, matrix2], axis=0)
print("Concatenated array:\n", concat)

# Split arrays
split = np.split(range_arr, 2)
print("Split arrays:", split)



Reshaped array:
 [[1 2]
 [3 4]]
Flattened array: [1 2 3 4]
Concatenated array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Split arrays: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [62]:
# Mean
print("Mean:", np.mean(arr))

# Median
print("Median:", np.median(arr))

# Standard deviation
print("Standard deviation:", np.std(arr))

# Sum
print("Sum:", np.sum(arr))


Mean: 2.5
Median: 2.5
Standard deviation: 1.118033988749895
Sum: 10


In [63]:
# Determinant
from numpy.linalg import det
matrix = np.array([[1, 2], [3, 4]])
print("Determinant:", det(matrix))

# Eigenvalues
from numpy.linalg import eig
eigenvalues, eigenvectors = eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Determinant: -2.0000000000000004
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [64]:
# Random integers
random_ints = np.random.randint(0, 10, size=(2, 3))
print("Random integers:\n", random_ints)

# Random floats
random_floats = np.random.rand(3, 3)
print("Random floats:\n", random_floats)

# Seed for reproducibility
np.random.seed(0)


Random integers:
 [[8 4 2]
 [7 0 7]]
Random floats:
 [[0.48935582 0.07169602 0.04677588]
 [0.8150443  0.11056826 0.07216199]
 [0.14045299 0.59791477 0.5208379 ]]


# Scikit-Learn

In [65]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [66]:
from sklearn.model_selection import train_test_split

# Sample data
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([0, 1, 0, 1])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [67]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [68]:
#Label Encoder
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)


In [69]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Sample data (replace with your actual data)
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([0, 1, 0, 1])

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Check unique classes in the training data
print("Classes in training data:", np.unique(y_train))

# Initialize and train the model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)
print("Predictions:", y_pred)


Classes in training data: [0 1]
Predictions: [0 1]


In [70]:
# Model Evaluation
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

class_report = classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

Accuracy: 0.0
Confusion Matrix:
 [[0 1]
 [1 0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       1.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0



# IT154 Ashish Vinod